format = """
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$env_var\
$sudo\
$cmd_duration\
$terraform\
$line_break\
$status\
$shell\
$character"""

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = 'bold dimmed green'

[username]
disabled = true

[hostname]
disabled = true

add_newline = false

[line_break]
disabled = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[directory]
style = "blue"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "green"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
